### ISSUE TITLE
Generator creates CoffeeScript file even if not using it

### ISSUE THREAD

**Issue by joeczucha** [TrestleAdmin/trestle#10]
Steps to reproduce: 

    rails new testproject --webpack --skip-turbolinks --skip-test --skip-action-cable && cd testproject

Remove `gem 'coffee-rails', '~> 4.2'` from Gemfile and, if applicable, any references from /app/assets/javascript/application.js

Add `gem 'trestle'` to Gemfile and run `bundle install`

Run `rails generate trestle:install`

    Running via Spring preloader in process 80339
          create  config/initializers/trestle.rb
          create  app/assets/stylesheets/trestle/_variables.scss
          create  app/assets/stylesheets/trestle/_custom.scss
          create  app/assets/javascripts/trestle/custom.js.coffee
          create  app/admin

Thanks for your work on the project.

**Comment by spohlenz** [comment]
Trestle's core JavaScript is currently written in CoffeeScript. However I have been considering rewriting this in plain JS (which shouldn't be too hard) so that I can remove the extra dependency on `coffee-rails`.

The trend seems to be away from CoffeeScript and towards ES6 / Babel / Webpack, which I do find appealing. However at this stage the extra complexity and losing support for older Rails versions is not desirable, so it will likely end up being vanilla JS.

**Comment by matthewd** [comment]
@spohlenz check out [the rake task](https://github.com/rails/rails/blob/3645263237bed08bb3edcb8cc7fc2284f02b58a1/actioncable/Rakefile#L38-L44) and [blade config](https://github.com/rails/rails/blob/3645263237bed08bb3edcb8cc7fc2284f02b58a1/actioncable/blade.yml) for how we do it in Action Cable: developing in CoffeeScript, but shipping compiled JS in the gem. (The final piece being that we [don't ship `app/`](https://github.com/rails/rails/blob/3645263237bed08bb3edcb8cc7fc2284f02b58a1/actioncable/actioncable.gemspec#L20); you have other assets, so would want to be a bit more selective there.)

**Comment by spohlenz** [comment]
Thanks @matthewd. That looks to be exactly what I need.

Have you looked into using Blade (or another tool -- I guess plain Webpack + Rake task would do it) to precompile ES6 before shipping, or have you been happy just using CoffeeScript?

**Comment by matthewd** [comment]
It looks like we're gearing up to do that on Active Storage (https://github.com/rails/rails/blob/master/activestorage/webpack.config.js, plus `app/javascripts` vs `app/assets`), but I hold out some hope we can get to an arrangement closer to Action Cable's before release.

The nice feature of the Blade setup is that there's no compiled version in git: if you run from the repository, it uses the coffee source [and thus requires coffeescript]. So there's no annoying extra compile step when working on the gem itself, yet when run from the distributed gem there's no coffee in sight.

**Comment by spohlenz** [comment]
The dependency on CoffeeScript has been removed in the latest commits, and I'll put out a new release in the next couple of days.

I ended up not implementing a fancy build process and simply rewrote the `.coffee` files in vanilla JS. Due to the nature of the JavaScript involved (mostly just initializing some jQuery plugins), I decided it wasn't worth the added complexity. However I am happy to revisit this in future as both the ecosystem and the complexity of the built-in JS changes.
