### ISSUE TITLE
Singular resource builder

### ISSUE THREAD

**Issue by willtcarey** [TrestleAdmin/trestle#109]
We love Trestle here at our company for writing up easy admin interfaces! Thank you for all of your work!

One thing we have come up against several times is the need to implement an editing interface for a single entity, one that isn't part of a collection, e.g. editing your own personal user profile. Some of the main differences would be we wouldn't need the table index view, only an edit view, and we wouldn't need any of the collection logic from the `Trestle::Resource` class.

I'm happy to take a first pass at implementing this but I can see a couple different ways of going about it and I wasn't sure if you had a preference on one vs the other. 

One option would be to turn this singular resource into an option of `Trestle::Resource` builder,
```
Trestle.resource(:my_user, singular: true) do
  ...
end
```
The problem I'm seeing going down that path is there are quite a few conditionals that would introduce into the Resource class and it would make some methods meaningless, for example what would it mean to override the `collection` for a singular resource?

The second option I was thinking was introduce a new subclass of `Trestle::Admin` which is `Trestle::SingularResource` and we could do
```
Trestule.singular_resource(:my_user) do
  ...
end
```
This would only generate routes for an edit page, not an index page and the sidebar item would link straight to the edit page. We'd probably also need an method to load whatever instance you're going to be editing
```
instance do
  # Load an instance of your model
end
```
And whatever else winds up coming up to support that.

Do you have any preferences on one direction over the other? Do you have a completely different way of handling singular resources?

Let me know what you think! Thanks!

**Comment by spohlenz** [comment]
Hi @willtcarey. This would be great! I actually started implementing this for a client recently, but ended up running out of time and went with a bare-admin approach with custom actions.

I've pushed my progress to the `singular-resources` branch: https://github.com/TrestleAdmin/trestle/tree/singular-resources

It uses the `singular: true` option like in your initial suggestion. I prefer the aesthetics of that compared to `singular_resource` (and it's probably too late to switch to `resource`/`resources` to mirror the Rails routing methods). At this stage I don't think the number of conditionals will be too bad -- methods like `collection` would just be ignored. However the builders could be altered to create a `SingularResource` subclass if it were to get out of hand.

The `instance` block must be defined, as well as the `model:` option if it can't be inferred from the admin name (which I think could potentially be common for the use cases of singular resources). I think the `instance` block is a hard requirement, even so far as suggesting an exception is raised if it isn't defined.

With the small number of changes in my branch, this mostly works already. However there are a few issues to resolve:

1. Breadcrumbs should be more specialized for singular resources (e.g. rather than "Home / Accounts / Editing Account" use "Home / Account"). One exception would be the `new` action.
2. If the `instance` block returns nil, automatically redirect to the `new` action.
3. The `id` parameter is being redundantly passed to form and link targets, and redirect locations. Not sure at this stage how to best solve this one -- open to suggestions.

If you'd like to run with this (and it would be much appreciated from me), feel free to create a PR for the WIP and we can collaborate and discuss further.

**Comment by spohlenz** [comment]
Looking at my code again with fresh eyes, I feel like maybe I was closer to realizing this feature than I thought. A few additional thoughts:

> 1. Breadcrumbs should be more specialized for singular resources (e.g. rather than "Home / Accounts / Editing Account" use "Home / Account"). One exception would be the new action.

This is probably just a matter of a few conditionals in the views. A little ugly but not too bad.

> 2. If the instance block returns nil, automatically redirect to the new action.

Another conditional in the controller, shouldn't be too big a deal.

> 3. The id parameter is being redundantly passed to form and link targets, and redirect locations. Not sure at this stage how to best solve this one -- open to suggestions.

I think a new `instance_path(instance, action:)` method within the Resource class would convert lines like `admin.path(:show, id: admin.to_param(instance))` into `admin.instance_path(instance, action: :show)`, enabling a conditional for singular resources and also reducing duplication within the controller and views.

Alternatively, the `path` method could be overloaded to allow passing an instance instead of an action as the first parameter. I don't hate this idea, but maybe it's too much magic? Would have to see how it plays out.
