### ISSUE TITLE
Current ExecJS runtime does't support ES6. Please install latest Node.js.

### ISSUE THREAD

**Issue by daniyalhussain** [TrestleAdmin/trestle#133]
Hi There, 

Yesterday i opened a issue with the sprocket 4, that issue is solve. Now i get another error: Current ExecJS runtime does't support ES6. Please install latest Node.js.

I use the installing steps:

 `$ rails generate trestle:install
$ rails generate trestle:resource Customer
`
Here is a picture of the error: 
![image](https://user-images.githubusercontent.com/5901712/43075887-80edd476-8e82-11e8-9ce0-7dbb1f8c37e3.png)

Node version is v9.9.0. 
Rails version is 5.2.0.rc1.
Ruby version is  2.5.0p0.

I searched for the error they might be a problem with the autoprefixer-rails 9.0 version.

**Comment by spohlenz** [comment]
This looks to be due to https://github.com/ai/autoprefixer-rails/issues/137 so we will likely have to wait for them to fix it (although I am working on modernizing the way assets work which will allow us to drop the dependency on `autoprefixer-rails`).

I would suggest trying the steps [here](https://github.com/ai/autoprefixer-rails/issues/137#issuecomment-406329798) if you have `therubyracer` in your Gemfile, or alternatively pinning `autoprefixer-rails` to a previous version in your Gemfile.
