### ISSUE TITLE
Any info/reasoning for the LGPLV3 licensing?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#140]
Just curious... no judgment but lots of people get concerned about this type of thing.

The project I'm using Trestle on is open source and MIT licensed generally.  It's for a different (unrelated) software project but I'm building everything out in the open. I'm using Trestle for CMS reasons and I do plan to modify trestle to a point of which it isn't really original.

I'm not open sourcing it for the purposes of distributing this, merely to collaborate it out in the open.  The codebase won't be meant to be used outside of this project because it doesn't really benefit anyone to since it's tied to our models and things.

But it muddies the waters a bit since it's LGPL so I was just curious.

**Comment by jfrux** [comment]
It also might cause people to not want to write plugins for it... I've seen that happen a lot too... if you're looking to build an eco-system around OSS plugin development, developers want to know you're fully committed as well.

**Comment by spohlenz** [comment]
This is fair question and one that definitely deserves a response here to clarify the future direction of the project.

As you and others may have guessed based on the license choice, I do intend to offer a commercial-friendly license of Trestle at some point in the future, along with paid plugins and support. Projects such as Sidekiq by Mike Perham have shown that this is a great way to sustainably support the development of an open source project of this size. I believe this model is a good fit for Trestle and if I could have a fraction of the success that Mike has had, I would be very happy indeed.

Having said that, I don't want to hinder projects like yours in any way. Whilst contributions you make to Trestle itself must also be LGPL-licensed, your application and plugins you write don't necessarily have to be. My intention is to be able to provide a framework for plugins such that, unless you are doing something extreme, then most changes can be made via hooks (or other future plugin-related APIs). That way you can keep the majority of your code licensed in a way that you prefer.

I'm more than happy to discuss further any licensing concerns you may have either here or offline (my email is in my profile). Otherwise if you have any particular modifications that Trestle doesn't currently have appropriate hooks for, please file an issue or PR.

**Comment by jfrux** [comment]
Thank you for the great response.
I love what you're doing and fully support your efforts of monetizing things a bit.

I agree that these types of things offer value and I think as long as people continue to trust Rails, they will continue to trust Trestle. :)

**Comment by asecondwill** [comment]
>  do intend to offer a commercial-friendly license of Trestle at some point in the future, along with paid plugins and support.

Just wanted to say this is great news.
