### ISSUE TITLE
save by enter

### ISSUE THREAD

**Issue by x-ror** [TrestleAdmin/trestle#168]
Do we possibility to save changes by clicking on an enter?

**Comment by spohlenz** [comment]
I'd definitely like to enable this as an option, with <kbd>⌘</kbd>+<kbd>S</kbd> / <kbd>CTRL</kbd>+<kbd>S</kbd> as the default shortcut for saving.

Given that Trestle currently does a refresh when submitting the form, I've found that enter to save the form can potentially be disruptive depending on the form controls, which is why it is disabled by default.
