### ISSUE TITLE
JQuery UJS conflict with Rails UJS

### ISSUE THREAD

**Issue by cguess** [TrestleAdmin/trestle#193]
When using "rails-ujs" (which is default in Rails 6, and usually recommended for 5.2+) There's a conflict with JQuery's own implementation. The error specifically is `Uncaught Error: If you load both jquery_ujs and rails-ujs, use rails-ujs only.`

Since I can't easily disable Trestle's use of JQuery I instead opted to comment out the Rails implementation. This seems to work, but I'd prefer to eventually move to the proper method to do this.

I can make a pull request at some point if you'd like, but just thought I'd give a heads up for the oncoming tide of Rails 6.

**Comment by spohlenz** [comment]
Thanks for the heads up. It definitely sounds like something I need to look into further (good timing too since I'm about to push a fairly major update to the assets).

How is rails-ujs being pulled in though? Are you requiring it explicitly in `trestle/custom.js` in order to use it with your own custom code? If so, is rails-ujs giving you anything that jquery_ujs doesn't provide?

**Comment by cguess** [comment]
For Rails 6.0 it's included by default in `/app/javascripts/packs/application.js` (looks like `require("@rails/ujs").start()`

I just checked and it's not the default with Rails 5.2.3, so it's must be only in the new version.

I'm not sure of benefits on either side, but since it'll be included by default it'd probably make more sense to check which version of Rails you're running and stick to one or the other.

**Comment by spohlenz** [comment]
Trestle includes its own isolated assets, so should not be affected by the default assets of new Rails versions.

Nevertheless I would like to stay on a supported path with things like this, so I have updated to rails-ujs in #195. This also provides a pathway towards eventually migrating away from jQuery.
