### ISSUE TITLE
Pre-fill form inputs according to url params

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#20]
Let it be two entities: Product and Category

On Category index page i have a column with a button:

```html
    <a href="/admin/products/new?category_id=666">Add product</a>
```

If i click it i expect that a category dropdown list be pre-selected with corresponding option...

i can imagine two ways to get universal solution for any **default** form:

1 javascript
2 modify trestle's form builder

and the first one seems more reasonable for me for now if ...?

**Comment by spohlenz** [comment]
Coincidentally I'd committed a solution to this last night but only to a local branch. I've just cherry-picked it in ea5e916389ff534fcd45f9becc63c3be01a77125.

Due to strong parameters, this won't automatically prefill the object. However it now makes it possible to override `build_instance` (and `update_instance`) with the full params hash as an optional extra parameter. e.g.

```ruby
# attrs - permitted params for the resource
# params - full params hash
build_instance do |attrs, params|
  Product.new(attrs).tap do |product|
    product.category_id = params[:category_id]
  end
end
```

This also makes STI resources possible:

```ruby
build_instance do |attrs, params|
  case params[:type]
  when :subclass
    Subclass.new(attrs)
  else
    ParentClass.new(attrs)
  end
end
```
