### ISSUE TITLE
Rails 6 DEPRECATION WARNING: Initialization autoloaded

### ISSUE THREAD

**Issue by thomasdarde** [TrestleAdmin/trestle#211]
When running specs in rails 6.0.0rc1 in my app , I have this warning :

`DEPRECATION WARNING: Initialization autoloaded the constants Trestle::AvatarHelper, Trestle::ContainerHelper, Trestle::DisplayHelper, Trestle::FlashHelper, Trestle::FormHelper, Trestle::FormatHelper, Trestle::GridHelper, Trestle::HeadingsHelper, Trestle::HookHelper, Trestle::I18nHelper, Trestle::IconHelper, Trestle::NavigationHelper, Trestle::PaginationHelper, Trestle::PanelHelper, Trestle::ParamsHelper, Trestle::SortHelper, Trestle::StatusHelper, Trestle::TabHelper, Trestle::TableHelper, Trestle::TimestampHelper, Trestle::ToolbarsHelper, Trestle::UrlHelper, Trestle::Controller, Trestle::Controller::Breadcrumbs, Trestle::Controller::Callbacks, Trestle::Controller::Dialog, Trestle::Controller::Helpers, Trestle::Controller::Layout, Trestle::Controller::Location, Trestle::ApplicationController, ActionText::ContentHelper, and ActionText::TagHelper.`

Anyone seeing the same issue ? A solution doesn't seem easy to implement

**Comment by spohlenz** [comment]
Thanks for reporting. I'll try to look into this issue with the new Rails autoloader sometime this week.

As I haven't had a chance to load it up yet, is this just issuing the warning, or is it breaking the admin entirely?

**Comment by thomasdarde** [comment]
It's ok if you keep 

`config.load_defaults 5.2`

else you have this error at startup

```ruby
/usr/local/var/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader/callbacks.rb:15:in `on_file_autoloaded': 
expected file /Users/thomas/code/mojito-import/app/admin/client/admins.rb
 to define constant Client::Admins, but didn't (NameError)
```

**Comment by spohlenz** [comment]
Now that I've had some time to look into this, I'm struggling to reproduce either the deprecation warnings or the exception.

On a fresh Rails 6.0.0.rc1 app (with `config.load_defaults 6.0`) using `trestle` from the master branch, I can create a model and Trestle resource and access the admin in development mode without seeing any deprecation warnings. I can also add rspec-rails (`4-0-dev` branch) and run specs which hit the admin without any deprecation warnings.

The only thing I can think of is that your file naming does look a bit odd, and Zeitwerk might be more strict about that. How are you declaring the resource within `app/admin/client/admins.rb`?

Assuming this is a resource for managing `Client::Admin` models, I would expect it to be named `app/admin/client/admins_admin.rb` and be initialized with:

```ruby
Trestle.resource(:admins, scope: Client) do
  ...
end
```

**Comment by thomasdarde** [comment]
Ok, it seems the issue comes from those 2 lines in our initializer

```
require 'trestle-devise/controller_methods'
Trestle::ApplicationController.send(:include, Trestle::Auth::ControllerMethods)
```

They are linked with the auth process (with devise) , I will check for a different way to implement this

**Comment by spohlenz** [comment]
@thomasdarde If you haven't already, could you please try this out on the current trestle master branch? I recently moved `Trestle::ApplicationController` our of the autoload paths which I believe should help in this situation.

**Comment by thomasdarde** [comment]
Thanks for the follow up. It does not fix the issue. The two lines above should be moved from the initializer I think

**Comment by spohlenz** [comment]
I've finally had a chance to dive deeper into this issue, understanding the differences that Zeitwerk brings and why my original attempted fix was not the correct solution.

Since Trestle controllers load helpers from `app/helpers` which are autoloaded by Zeitwerk, then the controllers should also be autoloaded (and hence live in `app/controllers`). What I had neglected previously was that this also includes the admin-specific subclasses `Trestle::Admin::Controller` and `Trestle::Resource::Controller`. Along with the root `Trestle::ApplicationController`, I've moved these to live under `app/controllers`. This feels a little nicer anyway regardless of the autoload requirements.

To accomplish this, I also had to alter the admin builder classes to lazily reference these controller classes so that they were not loaded during initialization.

Finally, the traditional autoloads (with `ActiveSupport::Autoload`) that I was using throughout the codebase were causing issues with Zeitwerk so I've changed these to regular `require_relative` calls, apart from the Adapter classes which should only be loaded when explicitly referenced.

These changes are all currently only in master but should be fully backwards-compatible. I've gone over the testing setup to ensure that all supported Rails version configurations are properly tested.

Regarding your code example, you will need to make one change which is to perform the `include` within a `to_prepare` block. Something like this should work:

```ruby
require 'trestle-devise/controller_methods'
Rails.application.config.to_prepare do
  Trestle::ApplicationController.send(:include, Trestle::Auth::ControllerMethods)
end
```

However I am also in the process of adding support for Devise to trestle-auth. This still needs some documentation but you can try it out by updating trestle and trestle-auth to master and running:

```
$ rails generate trestle:auth:install -devise
```

**Comment by thomasdarde** [comment]
Excellent, it does fix my issue ! 
I will give a try to trestle and devise in the coming days

**Comment by vasilybodnarchuk** [comment]
@spohlenz thanks for detailed info. But I can solve my problem with your solution. 
I use:
`gem 'trestle'
gem 'trestle-search'
gem 'trestle-auth'
gem 'trestle-sidekiq'
gem 'devise'
`
Also, I did not integrate devise into `trestle-auth`

**Comment by thomasdarde** [comment]
Just documenting this if needed by someone,
To have the app using :zeitwerk, i did add this line to application.rb:

`Rails.autoloaders.main.ignore(Rails.root.join('app/admin'))`

**Comment by Ted-Tash** [comment]
Ran into this issue after upgrading to Rails 8, with the `config.load_defaults 8.0`

The first error was:
`Zeitwerk::NameError: wrong constant name Trestle-devise inferred by Module from directory (Zeitwerk::NameError)`

which was solved by renaming the directory to `trestle_devise` (with an underscore) which then meant Zeitwerk expected the module to be named `TrestleDevise`.

Renaming the module, and calling it correctly from the trestle initializer:
```ruby
require "trestle_devise/controller_methods"
Rails.application.config.to_prepare do
  Trestle::ApplicationController.send(:include, TrestleDevise::Auth::ControllerMethods)
...etc
```
worked for me
