### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by SemyzSerhii** [TrestleAdmin/trestle#239]
Hi!) can i use drag and drop for trestle? If yes, how?

**Comment by spohlenz** [comment]
It's definitely possible. However it's not something that is (currently) built into Trestle.

In order to implement drag and drop, you will need to add your own JavaScript, either into `app/assets/trestle/custom.js` or by including it in your `config/initializers/trestle.rb`:

```ruby
Trestle.configure do |config|
  config.hook(:javascripts) { javascript_include_tag("custom_sorting") }
end
```

In your JS, you can then initialize your sortable JS via classes or data attributes that you add to your form fields or templates.

I've used both of these libraries in the past for various Trestle projects:

* https://github.com/ilikenwf/nestedSortable
* https://github.com/SortableJS/Sortable

**Comment by swrobel** [comment]
See https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab-(with-reordering)
