### ISSUE TITLE
Admin option in table block to nested path resource

### ISSUE THREAD

**Issue by lphm** [TrestleAdmin/trestle#279]
Hello,

I have a Contact admin model which references many (has_many) contact emails.

I had  created Admin resource as :

`
Trestle.resource(:contact_emails, scope: Erp, model: Erp::ContactEmail) do
...
`

And in contacts_admin.rb file (on the same scope and directory as above), I  declare this :
`
table record.contact_emails, admin: :contact_emails do
...
`

But admin links on emails list table are target to `/contact/etc`  not to  `/contact_email/...`

I think that Trestle has not found admin  resources...

Thank for your help

**Comment by spohlenz** [comment]
In order to reference a scoped admin, you will need to refer to it with the full scope:

```
admin: :"erp/contact_emails"
```

I'll keep this issue open as there are a few enhancements that I should make to help in this situation:

1) Not require the full scope when referencing the admin from another admin in the same scope.

2) Raise an exception if the admin is explicitly provided but cannot be found, rather than silently falling back to the current admin.

**Comment by lphm** [comment]
Cool, thank you :)
