### ISSUE TITLE
Dependency on sass-rails

### ISSUE THREAD

**Issue by bbenezech** [TrestleAdmin/trestle#28]
I wonder if you can remove the sass-rails dependency and expose a precompiled CSS, leaving the possibility to use the .scss files opt-in instead:

 - no dependency beats anything else anytime
 - sass compilation in userland is hazardous at best since you can't be sure your variables won't collide with the user's someday. It is a big source of problematic issues
 - not sure you can maintain a public API from a stylesheet and not break Semver
 - sass-rails compilation will slow down dev `Trestle` first page load and global deployments for _all_ your users

My 2 cents.

**Comment by spohlenz** [comment]
I'm definitely open to a change in the build process, since there are some drawbacks to the current approach as you mentioned. In particular, the initial compilation time and the extra required dependencies.

However one of the important things I would like to retain, which I haven't found a 100% acceptable alternative for, is the ability to customize `$brand-primary` and other Trestle or Bootstrap variables so that the admin interface can be themed.

Frustratingly, Bootstrap (and some of the other dependencies) mix the coloring in with typography, layout, etc. It wouldn't be a dealbreaker to extract out a smaller 'theme.scss' file that could be compiled by the asset pipeline. However it is one additional file that needs to be kept in sync with dependencies, and it would increase the total CSS footprint a little.

If you have any suggestions, or know of some methods being used by other projects to solve this, I'd be interested in hearing them.

**Comment by bbenezech** [comment]
To be honest and blunt, I think you can take full ownership over the design.
How many of the project users will present Trestle as "Project X admin" to their own users?
After all, when you admin a blog, you go to "Drupal's admin" or "Joomla's admin", not "My little poney's admin".
End user are used to using portals, middlewares, protocol consumers, etc.
It even conforts me to know that you did this job (great design with attention to details) and won't offload it me "I did the hard part for you, please paint it as you like, have fun playing with infamous BS variables".

**Comment by spohlenz** [comment]
I think you raise a good point, in that the project may be better served by limiting the amount of 'supported' theming. I'd still like to still keep the basic color scheming, logos, etc. but limiting this may then make a pre-packaged CSS file possible, and hence a few less dependencies (as autoprefixer-rails can also go).

I'll definitely need to think on this further but I'll keep this issue open until then.

**Comment by bbenezech** [comment]
Applying the same logic, you can arguably change the `admin` scopes to `trestle`.
I'm thinking about the `app/admin` configuration folder and the `/admin` engine route scope, there might be others?

**Comment by spohlenz** [comment]
In #195, I've introduced a new build process that includes a precompiled bundle, also eliminating the dependencies on sass-rails and autoprefixer-rails.
