### ISSUE TITLE
Unable to use Devise Masquerade within Trestle Admin Panel

### ISSUE THREAD

**Issue by dwood-somniainc** [TrestleAdmin/trestle#288]
Normal links from within the rails environment, work without issue. But Devise Masquerade is not being recognized by Trestle Admin.

form do |user|
  concat link_to("Login As", masquerade_path(user)
end

It's not working...........How can I access the helper methods for **devise_masquerade** gem.

Best,
DW

**Comment by spohlenz** [comment]
In this case, you will probably need to refer to the route using `main_app.masquerade_path(user)`.

**Comment by dwood-somniainc** [comment]
For some odd reason its not working in the user_admins.rb 

` concat link_to("Login As", main_app.masquerade_path(_user))`

`undefined method `masquerade_path' for #<ActionDispatch::Routing::RoutesProxy:0x00007f3a181cbf98>
`

**Comment by spohlenz** [comment]
Looking into this further today, I saw that devise_masquerade has an additional layer of indirection with the route helpers, which is why my original suggestion did not work. Basically `masquerade_path` is not a route helper but a regular helper that generates the proper route helper.

I was able to get this working by adding the following to `config/initializers/trestle.rb`:

```ruby
  config.helper do
    delegate :user_masquerade_path, to: :main_app
  end
```

**Comment by alexandre-lion** [comment]
This is the solution working for me:

```
if Pundit.policy(current_user, User).masquerade?
  toolbar.link 'Become', masquerade_path(instance)
end
```

and in `config/initializers/trestle.rb`

```
config.helper do
  delegate :user_masquerade_index_path, to: :main_app
end
```
