### ISSUE TITLE
Has Many Relationship for new record - unable to get parent id

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#296]
Hi,
I have used https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab example to create this functionality and it works ok, given that the "parent" object is already created. 
If you are in process of creating the "parent" object, there is no "parent" id available. 
In the example, there is a select if no id is available, but it requires to select some "parent", while our is not created yet.

I there a way to just "save" the child record in the parent form and create object in DB when saving the "parent" object? As in this example the "child" object is instantly created, which requires "parent" in DB.

Thanks

**Comment by spohlenz** [comment]
Currently, for the pattern described in https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab, the parent object does need to be persisted in order to save the child objects.

For an alternative that doesn't require this, check out the solution in https://github.com/TrestleAdmin/trestle/issues/19#issuecomment-347499096. This may not be suitable in all cases though (particularly if you have a complex child model).

First-class support for this pattern is on the roadmap, and getting closer to the top of my list.

**Comment by quantavi** [comment]
> Currently, for the pattern described in https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab, the parent object does need to be persisted in order to save the child objects.
> 
This doesn't require parent, because of this code:
```ruby
if task.project
    hidden_field :project_id
else
    select :project_id, Project.all
end
```
this works, because if parent is not available it shows you select with other Projects to choose from. But there will be no current project on the list as it is not created yet.  

> For an alternative that doesn't require this, check out the solution in [#19 (comment)](https://github.com/TrestleAdmin/trestle/issues/19#issuecomment-347499096). This may not be suitable in all cases though (particularly if you have a complex child model).
> 
I have implemented this solution and it works good as the "tasks" are saved along the "project"
> First-class support for this pattern is on the roadmap, and getting closer to the top of my list.

That is great news!
