### ISSUE TITLE
How to make dynamically readonly form or resource ?

### ISSUE THREAD

**Issue by lphm** [TrestleAdmin/trestle#298]
I have several resources / forms which must "readonly" if they have a particulary custom state.

I can use the option "readonly: true" in Admin Resource initializer but how can I give a callback symlink ? For exemple "readonly: :readonly?" where "readonly?" is a method onto my model instance.

**Comment by spohlenz** [comment]
Specifying `readonly: true` within the Resource options will remove the new/create/edit/update/destroy actions and routes entirely, so that will not be the solution here.

I am currently back to working on the authorization branch of `trestle-auth`, which I think will be the best way to achieve this (indeed the code to make forms read only is already partly implemented [here](https://github.com/TrestleAdmin/trestle-auth/blob/authorization/lib/trestle/auth/extensions/form.rb#L8-L10)).

This branch currently only supports CanCanCan but support for Pundit, as well as a custom DSL is next on my list. My end goal with the DSL is that your situation could be solved with some code like the following within your resource:

```ruby
authorize do
  edit? do
    instance.is_editable?
  end
end
```

**Comment by lphm** [comment]
Perfect, `trestle-auth` readonly implementation is a good idea. Thank you !
