### ISSUE TITLE
Trestle admin expects different table name

### ISSUE THREAD

**Issue by EMRJ** [TrestleAdmin/trestle#306]
I have the following tables

1. users
2. roles
3. app_roles

```
class Role < ApplicationRecord
    belongs_to :user
 end
```

```
class User < ApplicationRecord
  has_and_belongs_to_many :roles
end
```

```
class AppRole < ApplicationRecord
   belongs_to :app
 end
```

I have the following form in app_admin
```
form do |app|
  text_field :name
  select :role_ids, Role.all, {label: "App Roles"}, multiple: true
   end
```

I have model called **app_role** and table called **app_roles** but getting the following error while saving the app
 **ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "apps_roles" does not exist
 LINE 8:  WHERE a.attrelid = '"apps_roles"'::regclass
  ):**

**Comment by spohlenz** [comment]
The join table for a has_and_belongs_to_many association should have both tables pluralized (and alphabetized), so your join table should be named apps_roles. See https://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association.

This is a Rails requirement rather than anything from Trestle.
