### ISSUE TITLE
Blank value coming through in form multiselect

### ISSUE THREAD

**Issue by johansenja** [TrestleAdmin/trestle#328]
I have a form in an admin page and the code looks a little something like this:
```
form do |item|
  select :property, OPTIONS, { label: "..." }, multiple: true
end
```

I also have some custom logic in the setter in the model:

```
class Item < ApplicationRecord
  validates :property, presence: { in: ... }  

  def property=(args)
    ...
    super(...)
  end
end
```

Currently when I submit the form, it also submits a blank value (eg params: `{ ... property: ["", "option1", "option2"] }`) - so far I have just been filtering `args` in the setter and rejecting blanks - but elsewhere in the app there shouldn't be any blank values passed in, and it would be nice for any unexpected values to raise an error.

I noticed here there is a similar pattern in the model setter here - https://github.com/TrestleAdmin/trestle/issues/142#issuecomment-414099504 - but are there any other ways I can fix this from within trestle? Not sure if this is a trestle thing or a select2 thing, but I've had a quick look at select2 but can't see any quick fixes which might help?

**Comment by spohlenz** [comment]
This is actually a Rails feature (see https://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select). For form fields which generate an array of values (e.g. collection check boxes, multiple select fields, etc.), Rails adds a hidden empty input field, as otherwise it becomes impossible to select zero options (since no parameter would be passed).

If you don't wish to update your own model setter to reject the blank item, you can define a custom `update_instance` block. Something like this should work:

```ruby
Trestle.resource(:items) do
  update_instance do |instance, attrs|
    attrs[:property] = Array(attrs[:property]).reject(&:blank?)
    instance.assign_attributes(attrs)
  end
end
```

I'd like to eventually implement a form object API/DSL that would make these types of transformations easy, but this would be my recommended approach for now.

**Comment by johansenja** [comment]
Thanks for the quick response and the detailed answer - works like a charm. The behaviour is a small annoyance but it makes sense I suppose. Closing because this is just what I needed

**Comment by johansenja** [comment]
For the record, I added a wiki entry for `update_instance` (and whilst I was there, `build_instance` too) https://github.com/TrestleAdmin/trestle/wiki/How-to:-custom-logic-for-updating-&-initialising-an-instance

**Comment by spohlenz** [comment]
That's a great write up! Thank you.
