### ISSUE TITLE
Default collapse a group in menu

### ISSUE THREAD

**Issue by mateuszbozek** [TrestleAdmin/trestle#332]
Hi, I've considered is the any possibility to collapse a groups in menu on the left by default ? For example i have group "Group_name" which I use in many models :
```
  menu do
    group "Group_name" do
     ....
    end
  end
```
By default all groups are not collapsed. I have lots of models grouped and want to collapsed almost all (only selected groups).
Is there any possibility ? 

Thanks for any answer or suggestion .

**Comment by quantavi** [comment]
I have checked the : "trestle/app/views/trestle/shared/_sidebar.html.erb" file. 
It looks like the only way to do it currently is to have the collapsed group ids in the cookie.
`collapsed = cookies["trestle:navigation:collapsed"].try(:split, ",")`

The collapsed variable is then used to add "collapsed" class to given `<ul>` element.
Maybe you could set the 'default' cookie group ids after login unless the cookie exists from previous visits.

**Comment by spohlenz** [comment]
I definitely like this idea and will work to get it implemented. The main challenge as @quantavi points out is to change how the expanded/collapsed state cookie is managed. My current thinking is to store it as a serialized hash (group => state) rather than an array, and to only store the state for explicitly toggled navigation items.

**Comment by spohlenz** [comment]
This has now been added in 549bafe43a08507ae615cf67e13cc889c566256c.

You can specify a navigation group to be collapsed by default with:

```ruby
menu do
  group :group_name, collapse: true do
    ...
  end
end
```
