### ISSUE TITLE
All params in the dialog are strings

### ISSUE THREAD

**Issue by vasilybodnarchuk** [TrestleAdmin/trestle#343]
Hello! I have a task to create new records in the dialog with already populated data. So, when I tied to call the dialog `build_instance` received only `Strings` as values. But, I need to receive other types.

Request dialog code:
```
            admin_link_to('new', admin: :items, action: :new,
                                 params: { element_id: 1, value: 0 },
                                 target: '_blank', class: 'btn btn-success btn-block',
                                 data: { behavior: 'dialog' })
```

Bind properties
```
build_instance do |attrs, params|
   puts {params}.   # result is !!! {"element_id"=>"1", "value"=>"0", "controller"=>"items_admin/admin", "action"=>"new"}
end
```

How can I avoid this? I would like to receive correct types in the `build_instance`.

**Comment by spohlenz** [comment]
This is unfortunately just how things work with Rails params passing (and HTTP params in general). All of the parameter keys and values are passed over the wire as strings, so without a schema to cast them to their correct values, the app can't (and shouldn't) automatically infer what they should be.

If you are passing your params down to ActiveRecord, then AR will automatically do the casting to the correct attribute type. If you are doing some kind of service object, I would recommend looking into the ActiveModel Attributes API in order to do something similar.
