### ISSUE TITLE
Sidebar items no longer alphabetical - eager load issue?

### ISSUE THREAD

**Issue by scarerkite** [TrestleAdmin/trestle#350]
The items in our Admin sidebar used to be ordered alphabetically, which was very useful.

Since switching to Rails 6.0.3.5 and Zeitwerk autoloader, these now come out in a different order when eager loaded.
We've looked at the Trestle source code to try to understand the ordering, and why this might have been affected.
However, we couldn't work out how it was being loaded.

We also tried to write a spec to demonstrate the problem but when we opened a screenshot (using `save_and_open_page`), the sidebar was empty, and we couldn't work out how to load the items in the spec either.

```
feature 'Navigation' do
  scenario 'Sidebar lists resources in order' do
    visit '/admin/scopes'
    page.save_and_open_page
    expect(page).to have_link("Automatic")
    expect(page).to have_link("Dialog")
    expect(page).to have_link("Posts")
    expect(page).to have_link("Scopes")
  end
end
```

Spec screenshot:

![test](https://user-images.githubusercontent.com/6461304/113161332-30d3ac80-9236-11eb-82e8-87bd91b734c6.png)

We have about 30 items in our app, so this is quite inconvenient for our admins.
It is replicable in a small toy app (development mode lists items alphabetically, production mode does not) as well, so it doesn't seem to be anything unusual in our set up.

Development (no eager loading, alphabetical):

![development](https://user-images.githubusercontent.com/6461304/113161373-3a5d1480-9236-11eb-8256-b14609101f16.png)

Production (eager loading, not alphabetical):

![production](https://user-images.githubusercontent.com/6461304/113161464-52349880-9236-11eb-9113-ccd8a5e75c9a.png)

Any help would be much appreciated, thank you!

**Comment by quantavi** [comment]
We add something like this to each _admin file:

```ruby
  menu do
    group I18n.t("menu_registration") do
      item :professional_cards, icon: "fas fa-user-tie", priority: 2
    end
  end
```

use priority to set the order of items :)

**Comment by timdiggins** [comment]
@spohlenz I've created a failing spec #353 that shows the problem here. 

It appears that zeitwerk will load items in arbitrary order (at least on linux) - this is down to the order of Dir.each_child (read [comment](https://github.com/fxn/zeitwerk/issues/92#issuecomment-543834270) and [code](https://github.com/fxn/zeitwerk/blob/ba58e94db90d022bf77f580dcf5d6f0bdb2e6a96/lib/zeitwerk/loader.rb#L674)).

Classic eager_loading deliberately sorts the files (see below) and I think that the registry is relying on this to get the sidebar to be in order (or to put it another way, perhaps this this might be regarded as  not a "supported feature" but instead just an emergent property of classic loading).

FYI Classic eager loading:

see https://github.com/rails/rails/blob/v5.2.5/railties/lib/rails/engine.rb#L477

```ruby
  def eager_load!
    ...
    Dir.glob("#{load_path}/**/*.rb").sort.each do |file|
    ...
  end 
```

**Comment by spohlenz** [comment]
Thank you @scarerkite for the report and @timdiggins for the fix.

The original alphabetical ordering was definitely a happy accident but it does seem a good idea to have a defined consistent ordering within the library.
