### ISSUE TITLE
How to sort using joined fields?

### ISSUE THREAD

**Issue by simPod** [TrestleAdmin/trestle#362]
I can sort table using columns of displayed model (A):

`column: name, sort: { field: name }`

Consider

```ruby
class A < ApplicationRecord
  belongs_to :b
```

How can I sort A using column of B?

From this https://github.com/TrestleAdmin/trestle/wiki/Sorting-Options it does not seem it's possible.

The real life use-case In your demo would be sorting movie by directors names.

table `movies` has columns `name, director_id`
table `directors` has columns `name`

How would movie sort by director name look like?

**Comment by spohlenz** [comment]
Within a `sort_column` block, you can use ActiveRecord scope and/or Arel methods to return a new ActiveRecord scope with the desired ordering.

Using the example of a `Movie` that `belongs_to` a `Director`, you could use:

```ruby
sort_column :director do |collection, order|
  collection.joins(:director).merge(Director.order(name: order))
end
```

I've updated the demo app with a slightly more complicated example of this (as it uses a `has_one :through` rather than a `belongs_to`). You can find that code here:

https://github.com/TrestleAdmin/RailsFlixDemo/blob/master/app/admin/movies_admin.rb#L16-L18
