### ISSUE TITLE
JS not loaded after Form Post/Submit

### ISSUE THREAD

**Issue by ariffinsetya** [TrestleAdmin/trestle#396]
Hi I want to ask if there is a way to load js after post, when the html is rendered?
I have implemented uppy to replace my file_field input in the trestle admin. And i currently load it like this 

```
document.addEventListener('turbo:load', () => {
    document.querySelectorAll('.uppy-file-input').forEach(fileInput => {
        window.uppyHelper.fileUpload(fileInput)
    });
})
```

And it works well. but after saving/submitting the form and the page is re-rendered my js is not loaded since no `turbo-load` event is triggered, i have tried `DOMContentLoaded` , even put it in `window.onload` but as the page is not reloaded it won't work.

I want to ask if there is a way to load the js after post? or is there any event that will be triggered after post, so i can hook up the js on that event?

**Comment by spohlenz** [comment]
The current method is to use the `Trestle.init` JS function which takes a callback that is invoked whenever a part of the DOM is appended/replaced. See https://github.com/TrestleAdmin/trestle/blob/master/frontend/js/core/events.js for more info, but this would probably look something like:

```js
Trestle.init(function(root) {
  $(root).find('.uppy-file-input').each(function() {
    window.uppyHelper.fileUpload(this);
  });
});
```

I am in the early stages of converting Trestle from this old-school method over to using Stimulus controllers with some Hotwire, although this has been slow going lately with my current workload. However this means the above method will eventually be deprecated.

Because of this, I would still recommend looking into using Stimulus with the current version of Trestle by defining your own `admin.js` pack and loading it with the following in `config/initializers/trestle.rb`:

```ruby
config.hook(:javascripts) do
  javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload'
end
```

**Comment by ariffinsetya** [comment]
Oh great news, looking forwards to stimulus in trestle.
So I can simply put this on a js inside `javascripts/custom/*`
```
Trestle.init(function(root) {
  $(root).find('.uppy-file-input').each(function() {
    window.uppyHelper.fileUpload(this);
  });
});
```
and load it to `javascripts/trestle/custom.js` is that right?
Will try this first and maybe refactor it to stimulus as you explained. Just need to get this thing works first.

**Comment by ariffinsetya** [comment]
It works really well thanks for the info @spohlenz
