### ISSUE TITLE
problem when creating an entity with a polymorphic relationship

### ISSUE THREAD

**Issue by MaximShaikovskiy** [TrestleAdmin/trestle#491]
Hello
![Screenshot from 2024-09-16 15-39-33](https://github.com/user-attachments/assets/20d30dd7-ceda-4c33-9f9f-2efe998f6e0e)
I get this error
`t.references :documents_block, polymorphic: true, null: false`
`has_many :documents, as: :documents_block, dependent: :destroy`
`belongs_to :documents_block, polymorphic: true`
Trestle.resource(:documents)
`
build_instance do |attrs, params|
    if params[:information_material_and_general_rule_id]
      scope =
        ::InformationMaterialAndGeneralRule
          .find(params[:information_material_and_general_rule_id])
          .documents
    else
      scope = ::Document
    end
    scope.new(attrs)
  end
`
`
form dialog: true do |document|
    if document.documents_block
      hidden_field :documents_block_id
    else
      select :documents_block_id, InformationMaterialAndGeneralRule.all
    end
`
![image](https://github.com/user-attachments/assets/7d583e56-4520-45e2-accc-ac005a93a8b4)
`gem 'trestle', '0.10.0.pre'`

**Comment by spohlenz** [comment]
For polymorphic associations, you'll need both the `_id` column as well as a corresponding `_type` column. In order to achieve this within a single select field, you might want to look into signed GlobalID -- check out [this article](https://www.mintbit.com/blog/using-signed-global-ids-with-polymorphic-select-fields-in-rails-forms) and [this GoRails episode](https://gorails.com/episodes/polymorphic-select-rails-globalid) for some ideas on how to implement.

**Comment by MaximShaikovskiy** [comment]
Dull again... How to delete this issue?
