### ISSUE TITLE
controller's respond_to.js is not consistent

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#55]
Here 
https://github.com/TrestleAdmin/trestle/blob/75577ea68d717808d9888c2e64305b8926a1d855/lib/trestle/resource/controller.rb#L32 

(same for `update` and `destroy` actions)

we can see `format.js` block in case of successful action. but it is absent in case of error here https://github.com/TrestleAdmin/trestle/blob/75577ea68d717808d9888c2e64305b8926a1d855/lib/trestle/resource/controller.rb#L34

Of course, I don't know why you add `format.js`, but all i can imagine - is to support an "in-place" resource editing..

If so, i would suggest to add those, as far as make `@instance = instance` to minimally serve js formatted requests out of the box with `/views/admin/{resource_name}/{show|create|update|destroy}.js.erb` views

Because now my way to get bootstrap modal with in-place resource's show page instead of redirect (it's hacky, i know, sorry for that) is to override redirect_to and define_layout with this

    <a href='#{admin_url_for instance}' data-toggle='modal' data-target='#modal'>edit</a>"

```ruby

    layout :define_layout

      def redirect_to *args
        if request.xhr?
          render 'admin/refresh.js.erb', instance: instance
        else
          super *args
        end
      end

      private

      def define_layout
        if request.xhr?
          false
        else
          'trestle/admin'
        end
      end

```

but even this (what am i expecting else with my code smell like this? =)) became broken since the update from 0.8.2 to 0.8.5 because now your controller serve js request by itself but with an empty block

so, hope you are preparing trestle for modal-bootstrapped in-place editing or, please, shade some light what is the reason of `format.js` blocks

**Comment by spohlenz** [comment]
First of all, sorry for taking so long to get back to you. Trying to get caught back up now.

You are right about the `format.js` blocks -- I had added them in order to enable some in-place editing. The missing ones were an oversight that has now been corrected (although any `.js.erb` views may now need a `<% if instance.valid? %>` check.

I have also now added the first pass at supporting modal dialogs for the built-in forms, as well as custom actions. Enabling it is as simple as specifying the `dialog: true` option on the form block.

```ruby
form dialog: true do |page|
  text_field :title
  text_area :body
end
```

<img width="1270" alt="screen shot 2017-11-08 at 9 53 24 pm" src="https://user-images.githubusercontent.com/7600/32546657-c09a0f72-c4cf-11e7-8a36-d509c926e89d.png">

The index table should automatically refresh when the form is successfully saved.

If you are using custom actions, you can load them in a dialog by setting the `data-behavior` attribute on the link to "dialog".

```html
<%= link_to "Custom action", admin.path(:custom), data: { behavior: "dialog" } %>
```

I'm hoping that this will fit in nicely with your application now, and that you can remove most of your customizations. Please let me know if you encounter any issues.

**Comment by hoangnv2107** [comment]
Hi Mr @spohlenz if i want to remove action delete in dialog, how will  i make ? Thanks you very much

**Comment by spohlenz** [comment]
@hoangnv2107 The delete action can be removed by adding `remove_action :destroy` within your resource definition. However this will remove the action everywhere including the index. In order to remove it only from the dialog, you will (currently) need to copy the `trestle/resource/show.html.erb` template from the source and remove the `toolbar(:secondary)` block.
