### ISSUE TITLE
Edit 'has_many' models inside the main model

### ISSUE THREAD

**Issue by brunnopleffken** [TrestleAdmin/trestle#64]
Trestle.io is awesome, but it **really** lacks a documentation. I'm in doubt about a simple thing, can you help me?

I have a main model `Office`, which has_many `OfficeImage`. I'd like do manage `OfficeImage` inside the details `Office` (add, edit, delete), in another tab just like the screenshot below:

<img width="971" alt="screen shot 2018-01-08 at 15 02 21" src="https://user-images.githubusercontent.com/3427344/34682110-0eb6ef9c-f485-11e7-8ef0-7445116dc45a.png">

What's the better approach for this?

**Comment by spohlenz** [comment]
There is a plan to eventually implement a "subresource" feature, allowing easy management of has_many associations, either inline or from a separate form. However here is how you would accomplish it in the mean time.

I'll use an example below of a Project that has_many Tasks. First we'll add the tab and table on the parent resource:

```ruby
Trestle.resource(:projects) do
  form do |project|
    tab :project do
      text_field :name
      text_area :description
    end

    tab :tasks, badge: project.tasks.size do
      table project.tasks, admin: :tasks do
        column :description, link: true
        column :done, align: :center
        column :created_at, align: :center
        actions
      end

      concat admin_link_to("New Task", admin: :tasks, action: :new, params: { project_id: project }, class: "btn btn-success")
    end
  end
end
```

The "New Task" link is probably the most complicated bit, but we want to ensure that we pass the project id as a parameter when building the task. To actually use this, we need to override the `build_instance` block in the child (Task) resource:

```ruby
Trestle.resource(:tasks) do
  build_instance do |attrs, params|
    scope = params[:project_id] ? Project.find(params[:project_id]).tasks : Task
    scope.new(attrs)
  end
end
```

This uses the Project association to build the new task if the project id is provided, otherwise it will ignore it and simply to `Task.new`. You'll need to make sure that your task form includes a `project_id` field somewhere, either via a select tag or hidden_field.

A couple of potential improvements are to load the task form within a dialog (which may or may not make sense for your use case), as well as to show the project select field depending on whether it has been previously set:

```ruby
form dialog: true do |task|
  if task.project
    hidden_field :project_id
  else
    select :project_id, Project.all
  end

  text_field :description
  check_box :done
end
```

I hope that all helps. You're definitely right about the documentation lacking right now, and it's taking way too long for me to get it out. However I've recently restructured my current WIP and it's making things progress much smoother.

**Comment by brunnopleffken** [comment]
Thank you so much @spohlenz, it worked like a charm! :)
Your tutorial should become a topic in the project Wiki.
