### ISSUE TITLE
Generic html (erb partial) page

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#7]
It would be nice to include into admin structure other than table pages with any custom html i want to insert. Like "Wiki" or "FAQ" or iframes with some analytics/graphs or ... . Are there any plans for this?

```ruby

Trestle.resource(:faq) do
  menu do
    group :info do
      item :faq, icon: "fa fa-question"
    end
  end

  page do
    render 'faq'# leading to _faq.html.erb partial
  end
end
```

or, maybe, even simpler within any other resource's `menu do;end` block

```ruby
Trestle.resource(:administrators, model: Trestle.config.auth.user_class, scope: Auth) do
  menu do
    group :configuration, priority: :last do
      item :administrators, icon: "fa fa-users"
    end
    group :info do
      page :faq, partial: 'faq'
      page :shmaq, partial: 'shmaq'
    end
  end
#...
end
```

Thanks

**Comment by spohlenz** [comment]
Yes! Right now you can use `Trestle.admin(:faq)` (instead of `Trestle.resource(:faq)`) and you will end up with a bare, single-page admin.

Here's an example based on a FAQ admin:

`app/admin/faq_admin.rb`:
```ruby
Trestle.resource(:faq) do
  menu do
    group :info do
      item :faq, icon: "fa fa-question"
    end
  end

  controller do
    def index
      # Optionally set instance variables here
      @faq = ...
    end
  end
end
```

`app/views/admin/faq/index.html.erb`:
```erb
<% content_for(:title, "FAQ") %>

<%= render layout: "layout" do %>
  Your FAQ content here.
<% end %>
```

In its current state, it's currently a bit raw. I'd like to add in a generator, as well as add a few more options to the template (to enable/disable wrapper, breadcrumbs, title, etc).

You can also add custom actions. This is a bit messy -- eventually I want to add a DSL for this:

```ruby
Trestle.resource(:faq) do
  controller do
    def custom
      # Will render app/views/admin/faq/custom.html.erb
    end
  end

  routes do
    get :custom
  end
end
```

**Comment by okliv** [comment]
i think there is a mistype `Trestle.resource(:faq) do` -> `Trestle.admin(:faq) do`

**Comment by spohlenz** [comment]
Oops, yes. Fixed. Thank you.

**Comment by spohlenz** [comment]
Just pushed `v0.8.3` to the gem servers which includes a generator for non-resourceful admins:

```
rails generate trestle:admin NAME
```
