### ISSUE TITLE
Theme customization

### ISSUE THREAD

**Issue by eshaiju** [TrestleAdmin/trestle#8]
Is it possible to customize theme color?.

**Comment by spohlenz** [comment]
After running the install generator (`rails generate trestle:install`), you will find a file in `app/assets/stylesheets/trestle/_variables.scss` that looks like this:

```scss
// This file may be used to override the Sass variables used within the Trestle
// admin. It will be automatically included within all admin pages.
//
// Both Bootstrap defaults as well as Trestle can be set here.
// For a detailed overview of the Trestle defaults, see the file
// `app/assets/stylesheets/core/_defaults.scss` within the Trestle source.

// Customize the overall Trestle theme color:
//
//   $brand-primary: #337ab7;
```

By uncommenting and changing the `$brand-primary` variable, you can customize the main admin theme color.

![trestle-theming](https://user-images.githubusercontent.com/7600/29053388-0b31511a-7c2f-11e7-8089-8ab0ec0d62ef.png)

**Comment by anatoliyarkhipov** [comment]
Is there a chance I need to do something special to make the `_theme.scss` file be picked up in Rails 6? I tried to define colors as in the [`_theme.scss`](https://github.com/TrestleAdmin/RailsFlixDemo/blob/cb167f992f2790a488deee162e3878a462e307c9/app/assets/stylesheets/trestle/_theme.scss) from the demo repo, but it seems my changes don't take any effect. This is how it looks like in my project (`color` for `h1` is ignored too):

![image](https://user-images.githubusercontent.com/1934180/82162867-3f300880-98b0-11ea-894d-46be018f8eca.png)

**Comment by spohlenz** [comment]
For theme compilation, you will need to have a Sass compiler in your Gemfile, either `sass-rails` or `sassc-rails` (recommended). Depending on your Rails defaults that may or may not have been added automatically.

`Gemfile`:
```ruby
gem 'sassc-rails'
```

**Comment by anatoliyarkhipov** [comment]
Even in Rails 6? Somewhere I read something they got rid of `sassc-rails` in 6. Did I mistake it? 🤔

**Comment by spohlenz** [comment]
Rails 6 comes with Webpacker as a partial replacement for the old Sprockets asset pipeline. However at this stage it is mainly targeted at JavaScript only, so for CSS compilation Sprockets is still generally the way to go. That will likely change eventually -- the whole transition has been a bit messy.

A new Rails (6.0.3) will include the following line in the Gemfile:

```
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
```

which now appears to just be a thin wrapper around `sassc-rails` (TIL!). As long as you have that in your Gemfile, then theme compilation should work.

**Comment by anatoliyarkhipov** [comment]
It seems I have that dep:

![image](https://user-images.githubusercontent.com/1934180/82165815-3266e100-98bf-11ea-9861-a5add1c84634.png)

Is there a chance you can explain how it's supposed to work? I'm new to Ruby and new to Rails, and it's still hard to figure out how things are glued together (or what are the conventions, I'd dare to say). 

This specific file, `_theme.css`, how it's supposed to be imported and compiled? Is there some generic assets compiling thing in Rails, which Trestle plugs itself into?

**Comment by spohlenz** [comment]
There's a little bit going on but I'll try to summarize the main parts:

1) In the [configuration](https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/configuration.rb#L26), `Trestle.config.theme` is set to true if Sass or SassC are available (or if manually set within `config/initializers/trestle.rb`).

2) In the [Trestle engine](https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/engine.rb#L30-L36), the file `trestle/theme.css` is added to the list of files to be precompiled, and the theme paths are added to the Sprockets paths.

3) The `trestle/theme.css` referenced in 2) actually points to this file [here](https://github.com/TrestleAdmin/trestle/blob/master/frontend/theme/trestle/theme.scss) rather than the SCSS partial within your `app/assets/stylesheets` folder. The `_theme.scss` partial is included from [here](https://github.com/TrestleAdmin/trestle/blob/master/frontend/theme/trestle/theme/_variables.scss#L15).

As far as troubleshooting goes I'd:

a) Make sure you have restarted your Rails server.
b) Try clearing the Sprockets cache with `rails tmp:cache:clear`.
c) Check the logs to see if any errors are being triggered when the file is accessed.
d) If all that fails, upload a Rails app to GitHub that demonstrates the issue and I'll take a look.

**Comment by twhitacre** [comment]
@spohlenz I'm having the same issue. 

I'm on the latest Rails `6.0.3.1` and using it as an API. I had to manually add the correct middleware to get Trestle to work and while it seems to work great, I can't get any of the SCSS files to work.

I've tried installing both `sass-rails` and `sassc-rails` and no matter what I do, neither the `_theme.scss` or `_custom.scss` are picked up.

If I manually set `Trestle.config.theme = true` in the `trestle.rb` file, a new theme file does show up, but it's not my theme file. It's another one from the gem.

**Comment by spohlenz** [comment]
@twhitacre I suspect that with a Rails API setup, there is a piece of configuration missing.

> If I manually set Trestle.config.theme = true in the trestle.rb file, a new theme file does show up, but it's not my theme file. It's another one from the gem.

This suggests that it might be the asset paths not being configured (i.e. your `app/assets` directory), as the Trestle theme will build with the defaults if it doesn't find your `_theme.scss` file.

Is it possible you could also share your middleware setup to get the base Trestle functionality working in your app? I'd love to get that properly supported without the manual workarounds.

**Comment by twhitacre** [comment]
@spohlenz Sure, so here's what I have so far:

First, I added the following to my `application.rb`:

```ruby
config.middleware.use ActionDispatch::Flash
config.session_store :cookie_store
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore, config.session_options
config.middleware.use ::Rack::MethodOverride  
```

Note that `config.api_only` is still set to `true` (didn't make a difference either way)
Also, I still have `require "sprockets/railtie"` commented out. (again, didn't make a difference)

If I do NOT set `Trestle.config.theme = true` in the Trestle config, then it will pick up the `app/assets/stylesheets/trestle/_custom.scss` but either way, it will not pick up the `_theme.scss` file.

So for now, I'm just putting all my style overrides in the custom file. It works because I have a few, but it would be nice to get the theme override to work.

My whole setup is pretty common. I often build an API only with Rails, stand up a React front end but then will set up a simple Admin panel for a client. I've usually used ActiveAdmin, but have found I like Trestle much better. This is the first time they've request I update the theme though.
