### ISSUE TITLE
How can i redirect_back page?

### ISSUE THREAD

**Issue by X-tymchenko** [TrestleAdmin/trestle#80]
```
return_to do 
  path(:index)# something like `path(:back_page)`
end
```

**Comment by spohlenz** [comment]
In d522ea0, you can now do `return_to { :back }` to perform a `redirect_back`.

Please note that the return_to blocks also now run in the context of the controller, so if you are using `path(:index)` in other places, you will need to change it to `admin.path(:index)`.

I'll be pushing a new gem release tomorrow.

**Comment by X-tymchenko** [comment]
@spohlenz `return_to { :back }`  If I call the method of editing a record from the index page. After saving again, go back to the edit page. So it should be?

**Comment by spohlenz** [comment]
That is correct -- the 'back' page is relative to the create/update/delete action, which will generally be the form page.

To go back further, you'll need to save a reference to the return location when editing the form. Something like this should work:

```ruby
form do |instance|
  concat hidden_field_tag :return_location, params[:return_location] || request.referer    
  # Rest of your form fields...
end

return_to do
  params[:return_location] || :back
end
```

**Comment by jfrux** [comment]
Does this apply to Modals?
It's grabbing the `closest('[data-context]')` which is the modal and it's blank.
This modal was spawned by a tab.

How do I set that modal context to be something other than blank?  I believe that's causing it to refreshMainContext() which is then causing it to lose the tab.

I've found if I delay the focusActiveTab() by 500ms it grabs the right tab.

I'm also thinking that since the data-context is blank, it's not closing the modal?
I'm not really seeing a call to close it honestly after save, but I might just add it into my local version.

**Comment by spohlenz** [comment]
@jfrux A custom `return_to` block likely won't work too well with dialog forms. I would like to add further options to either close or persist the modal after saving, but I've not looked at that yet.

Regarding the current active tab in the main context being lost, that should now be fixed in ffde791.

**Comment by jfrux** [comment]
I found that I had to set a delay in some cases or the tab switch didn't work in my solution... but I'll try out your solution and update. :) . Thanks!

**Comment by jfrux** [comment]
Yours is a lot less code than mine :D haha

**Comment by kxu1988** [comment]
> 

any update for "close the model after saving" ?
