### ISSUE TITLE
Using bootstrap 4 with trestle

### ISSUE THREAD

**Issue by BobWalsh** [TrestleAdmin/trestle#87]
Looking at your code (trestle/vendor/assets/bower_components/trestle/bootstrap-sass/assets/stylesheets/_bootstrap.scss) it looks like Trestle is using Bootstrap 3.3.7. How do I get it working with Bootstrap 4, which I'm using for the rest of this site?

**Comment by svoboda-jan** [comment]
Since this is a major version difference you can't simply switch to v. 4, it would require updating / fixing internal trestle views.

You can however use both versions, v. 4 for the site and keep v. 3 for the admin, since the site and admin are probably on different namespaces and use different layouts / stylesheets.

/cc @spohlenz

**Comment by spohlenz** [comment]
Bootstrap 4 support is coming soon (mainly waiting on dependencies to all update their support). As @svoboda-jan suggests, Trestle uses its own vendored copy of Boostrap so you can use Bootstrap 4 within your app without conflict.

**Comment by BobWalsh** [comment]
I REALLY like trestle! So much simpler to implement than active admin. Thank you!

**Comment by cguess** [comment]
@spohlenz Is there any updates on the progress towards Bootstrap 4?

**Comment by spohlenz** [comment]
@cguess I do now finally have an update on this front. I've been working for quite a few months on a fairly major update to the Trestle CSS/JS assets. This includes:

* Updating to Bootstrap 4 (currently 4.3.1)
* Updating other dependencies to their latest available versions
* Removing Ionicons from the default included icon sets (so only FontAwesome 5)
* Convert and reorganize JS assets to ES6
* Restructure and clean up SCSS assets
* Moving to a new build process using Webpack (not Webpacker though)
* Updating the way theming works (stripped right back)

This new build process has been a major pain to get working right, mainly due to the awkward state of asset handling in Rails right now. After much experimentation, I've landed on a solution that uses Webpack to build a precompiled asset bundle (committed to the repo and shipped with the gem) that is then included via Sprockets. This means that while Sprockets will be a dependency still, none of Webpacker, sass-rails (or sassc-rails) will be required (unless you want to customize the theme).

Since Bootstrap will be shipped in precompiled state, the existing theming options will have to be reworked. When Sass compilation is available, an additional stylesheet will be injected into the layout containing the CSS for the theme. Unfortunately this limits the theming to color adjustments only. At some stage in the future, I hope it will be possible to build a fully custom bundle by integrating with Webpacker.

As far as progress goes, here's a summary of what work is completed and what is left:

- [X] Build configuration
- [X] JavaScript conversion to ES6
- [ ] Bootstrap 4 conversion (Sass, form helpers, views) (~95% complete)
- [ ] Theme support (~10% complete)
- [ ] Update plugins

As soon as the Bootstrap 4 conversion is done, I'll be pushing it to a branch for testing and the remaining development. I anticipate this should be within the next week.
