### ISSUE TITLE
Cannot pass parameters to :new action

### ISSUE THREAD

**Issue by fxgallego** [TrestleAdmin/trestle#92]
I'm used to pass parameters in links to actions in order to associate one model with other without requiring the user to enter the associated one. For example, one of my new buttons is built using this code:
```slim
    = admin_link_to(admin: :milestones, action: :new, params: {milestone: {business_id: record.id}}, class: "btn btn-default btn-sm") do
      = icon("fa fa-plus")
      span class="sr-only"
        = t("admin.buttons.new", default: "New %{model_name}", model_name: 'Milestone')
```
Note that I'm providing the associated object in the params hash.
The default Trestle :new action ignores the params passing an empty hash for new objects. I know that I can override :new but that would be needed in all admins and maybe is something that could be considered as an enhancement to Trestle, but I'm not sure, or maybe there is another and better way to do the same. In any case the following patch does the job well for me.
```ruby
module Trestle
  class Resource
    class Controller < Admin::Controller

      def new
        self.instance = admin.build_instance(params.has_key?(admin.admin_name.singularize) ? permitted_params : {}, params)

        respond_to do |format|
          format.html
          format.json { render json: instance }
          format.js
        end
      end
    end
  end
end
```

**Comment by spohlenz** [comment]
I hadn't initially planned on supporting this, mainly due to the "ugliness" of passing in nested params as a GET query string. This is one of the reasons I added the additional `params` argument to the `build_instance` block, so that it could be customized in a more targeted fashion.

However it does seem that the benefits might outweigh the cons, and it would be opt-in anyway, so you may just have persuaded me.

**Comment by spohlenz** [comment]
This has now been added in a884990, and I'll be releasing 0.8.8 shortly.
