### ISSUE TITLE
Table actions build error (only when using table from other admin)

### ISSUE THREAD

**Issue by fxgallego** [TrestleAdmin/trestle#94]
This is an special case but I think that it's a bug.
I'm building a new resource with type admin because it represents a custom dashboard not a resource.
`Trestle.admin(:billing_dashboard) do` bla bla
This new :billing_dashboard resource has a view and uses a table to display invoices. The table is defined in the InvoicesAdmin and named as 'small'.
```ruby
table 'small' do
    column :client
    column :number
    column :date
    column :due_date
    column :payment_date
    column :net_amount
    column :total_amount
    column :payment_amount
    actions do |builder|
      builder.show
    end
```
As this table is used from an extern dashboard I don't want destroy actions for each row so I changed the actions to only build #show. Rendering this table in the context of InvoiceAdmin works ok but not when used from other admin.

The problem is in the admin option passed to the [`admin_link_to`](https://github.com/TrestleAdmin/trestle/blob/7811aba9dc47be9608e7e53a2b1721eff708460c/lib/trestle/table/actions_column.rb#L50) helper called from the ActionsColumn#button method. There is a reverse_merge that initializes de options with admin->nil and after that ends on [this test](https://github.com/TrestleAdmin/trestle/blob/7811aba9dc47be9608e7e53a2b1721eff708460c/app/helpers/trestle/url_helper.rb#L18) but admin options is nil so nil is passed to the lookup function.

I've found that a workaround to this is setting the admin when the table is defined but the problem is still there and I don't know which solution would be better for you.
Workaround:
```ruby
table 'small', admin: 'invoices' do
    column :client
    column :number
    column :date
    column :due_date
    column :payment_date
    column :net_amount
    column :total_amount
    column :payment_amount
    actions do |builder|
      builder.show
    end
```

**Comment by spohlenz** [comment]
I had initially thought that this might be tricky, since the `admin` option is used to determine whether the row should be automatically linked or not, and so passing the current admin might not be the correct behaviour when declared within a regular admin.

However I think the fix I have introduced in d8e4416 should handle this nicely. The `admin` option is always passed to all tables (named or not) declared within a resource. For tables within a regular admin, the admin must be passed explicitly.

Passing the admin option explicitly is what I have typically done for my dashboard tables to date, since I feel that it puts the table declaration closer to where it is used. However I definitely feel that your choice of putting the admin definition within the target resource is a valid and useful one, so thank you for reporting.
