### ISSUE TITLE
Show & Edit actions are the same?

### ISSUE THREAD

**Issue by kentnguyen** [TrestleAdmin/trestle#95]
Is this a WIP for Show action? I don't seem to be able to locate the renderer for Show page in source code.

**Comment by spohlenz** [comment]
In most cases, separate show and edit actions are redundant, since the edit view shows you the data anyway. Having a separate edit action simply adds an extra click, and more things to define in the DSL.

There are certainly cases where this isn't true though, in particular where the back-end workflow should be more tightly controlled. A good example of this is an order view in an e-commerce application. Or perhaps you want to implement some form of locking when a user is editing a resource.

In this case, Trestle leaves it up to you as to how you want to customize the show template. The edit action duplicates the show template, so that you can link to it from your custom show page.
